dist: 
  - xenial
  - focal

sudo: required

language: cpp

compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - lcov

install:
  - source ci/travis/install_lcov.sh
  - source ci/travis/install_pinocchio.sh
  - sudo apt install libeigen3-dev

script:
  - mkdir -p build  && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DTESTING=True
  - travis_wait 120 cmake --build . --config Debug
  - ctest --output-on-failure

after_success: 
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' '/opt/*' '"${HOME}"/.cache/*' '*/googletest/*' '*/test/*' '*/c++/*' '*/pinocchio/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"
