var searchData=
[
  ['backward_5friccati_5frecursion_5ffactorizer_2ehpp_0',['backward_riccati_recursion_factorizer.hpp',['../backward__riccati__recursion__factorizer_8hpp.html',1,'']]],
  ['backward_5friccati_5frecursion_5ffactorizer_2ehxx_1',['backward_riccati_recursion_factorizer.hxx',['../backward__riccati__recursion__factorizer_8hxx.html',1,'']]],
  ['backwardcorrection_2',['backwardCorrection',['../classidocp_1_1_unconstr_backward_correction.html#a46225dbcdf112e710e9080fa2c834124',1,'idocp::UnconstrBackwardCorrection']]],
  ['backwardcorrectionparallel_3',['backwardCorrectionParallel',['../classidocp_1_1_unconstr_split_backward_correction.html#a1f7fef79fed363120a1fa7ca0c4e7d1b',1,'idocp::UnconstrSplitBackwardCorrection']]],
  ['backwardcorrectionserial_4',['backwardCorrectionSerial',['../classidocp_1_1_unconstr_split_backward_correction.html#ac49955570c42752016b1bf67086e87c8',1,'idocp::UnconstrSplitBackwardCorrection']]],
  ['backwardriccatirecursion_5',['backwardRiccatiRecursion',['../classidocp_1_1_unconstr_riccati_factorizer.html#a7ecb7c72cd65d01af07580c91df15741',1,'idocp::UnconstrRiccatiFactorizer::backwardRiccatiRecursion()'],['../classidocp_1_1_unconstr_riccati_recursion.html#a70f925fd138de646f2e169dbf99362ce',1,'idocp::UnconstrRiccatiRecursion::backwardRiccatiRecursion()'],['../classidocp_1_1_riccati_recursion.html#a4a7031ed1fcb0b453f6abf3e4f8babd0',1,'idocp::RiccatiRecursion::backwardRiccatiRecursion()'],['../classidocp_1_1_riccati_factorizer.html#ad4b93de11211aaaa61453f966b0231df',1,'idocp::RiccatiFactorizer::backwardRiccatiRecursion(const SplitRiccatiFactorization &amp;riccati_next, ImpulseSplitKKTMatrix &amp;kkt_matrix, ImpulseSplitKKTResidual &amp;kkt_residual, SplitRiccatiFactorization &amp;riccati)'],['../classidocp_1_1_riccati_factorizer.html#aae4ff393278ab091ceeae1afd23ade2d',1,'idocp::RiccatiFactorizer::backwardRiccatiRecursion(const SplitRiccatiFactorization &amp;riccati_next, SplitKKTMatrix &amp;kkt_matrix, SplitKKTResidual &amp;kkt_residual, const SplitSwitchingConstraintJacobian &amp;sc_jacobian, const SplitSwitchingConstraintResidual &amp;sc_residual, SplitRiccatiFactorization &amp;riccati, SplitConstrainedRiccatiFactorization &amp;c_riccati, LQRPolicy &amp;lqr_policy)'],['../classidocp_1_1_riccati_factorizer.html#a9bbdc300adb840c165ad53c375ce2b89',1,'idocp::RiccatiFactorizer::backwardRiccatiRecursion(const SplitRiccatiFactorization &amp;riccati_next, SplitKKTMatrix &amp;kkt_matrix, SplitKKTResidual &amp;kkt_residual, SplitRiccatiFactorization &amp;riccati, LQRPolicy &amp;lqr_policy)']]],
  ['backwardriccatirecursionfactorizer_6',['BackwardRiccatiRecursionFactorizer',['../classidocp_1_1_backward_riccati_recursion_factorizer.html#ad39fc95569f750f3dcd4634c32f98426',1,'idocp::BackwardRiccatiRecursionFactorizer::BackwardRiccatiRecursionFactorizer(const Robot &amp;robot)'],['../classidocp_1_1_backward_riccati_recursion_factorizer.html#a5ad56a64d1b1be8702adbbcd0d907eee',1,'idocp::BackwardRiccatiRecursionFactorizer::BackwardRiccatiRecursionFactorizer()'],['../classidocp_1_1_backward_riccati_recursion_factorizer.html#a7779ccf69c32954ddde9515659268f1b',1,'idocp::BackwardRiccatiRecursionFactorizer::BackwardRiccatiRecursionFactorizer(const BackwardRiccatiRecursionFactorizer &amp;)=default'],['../classidocp_1_1_backward_riccati_recursion_factorizer.html#afbf833ad80140235af4096638a10a1de',1,'idocp::BackwardRiccatiRecursionFactorizer::BackwardRiccatiRecursionFactorizer(BackwardRiccatiRecursionFactorizer &amp;&amp;) noexcept=default'],['../classidocp_1_1_backward_riccati_recursion_factorizer.html',1,'idocp::BackwardRiccatiRecursionFactorizer']]],
  ['barrierparameter_7',['barrierParameter',['../classidocp_1_1_constraint_component_base.html#aac4f5a7fe815abb973c421dd8af6feab',1,'idocp::ConstraintComponentBase::barrierParameter()'],['../classidocp_1_1_impulse_constraint_component_base.html#a2681e5640304b2631c31cd4b88264ee4',1,'idocp::ImpulseConstraintComponentBase::barrierParameter()']]],
  ['basejointtype_8',['BaseJointType',['../namespaceidocp.html#a750b6f29ee552fdb3779b9005c58969b',1,'idocp']]],
  ['beta_9',['beta',['../classidocp_1_1_impulse_split_solution.html#aaaeb929a90b4eda2011b31852c402207',1,'idocp::ImpulseSplitSolution::beta()'],['../classidocp_1_1_split_solution.html#addd308f77733c0dd2ffacbd9c02adcf0',1,'idocp::SplitSolution::beta()']]]
];
